### ISSUE TITLE
An error occurred while running docker

### ISSUE THREAD

**Issue by nana-zhang** [ins-amu/tvb-pipeline#3]
Hello, 
       First of all, I pulled the image. Then I tried to run with **docker**, but an error occurred, I'm not sure whether my command is correct, so I hope you can give me some suggestions, as shown in the figure below：
![Screenshot from 2022-08-05 16-05-20](https://user-images.githubusercontent.com/70929994/183037983-1c32157c-cc3e-403b-84cc-5c11410bd8fc.png)
       I don't know what address ‘**/ path / to / TVB make / docker / run**’ represents. I found ‘**docker / run**’ in TVB pipeline, so I guess it is the address where the **TVB pipeline package** is stored.Then the error shown above appears. I hope you can give me some suggestions to correct my error.

**Comment by maedoc** [comment]
The `docker/run` script creates a Docker container, tho it seems to be not working in your case.  What does `docker images` say?

**Comment by nana-zhang** [comment]
Hello, I may have misunderstood it at the beginning. I thought it was necessary to pull the  image. Now I seem to understand it. I don't need to pull the image. I can run the docker directly using the / docker / run script. However, this problem does not seem to have much to do with whether I pull the image. So how can I solve this bug?

**Comment by nana-zhang** [comment]
Hello, I may have misunderstood it at the beginning. I thought it was necessary to **pull the image**. Now I seem to understand it. I don't need to pull the image. I can run the docker directly using the / docker / run script. However, this problem does not seem to have much to do with whether I pull the image. So how can I solve this bug?  Is it because of the **environment**?

**Comment by maedoc** [comment]
The `docker/run` script is just a wrapper for creating and running the container.  I can't tell from the screenshot what's wrong, which is why I asked for more information.

**Comment by nana-zhang** [comment]
Hello, let me briefly describe my operation process:
1. I installed **Docker**
2. I used the command **"docker pull maedoc/tvb-make"** to pull the image
3. Clone the **tvb-pipeline** package locally
4. Prepare T1 data and put it into the corresponding folder
5. Run the command according to the instructions of **Docker** in **readme**

Then there is an error in the figure. Is there a problem with my step?

**Comment by maedoc** [comment]
Thanks, I suspect there is a problem with the Docker image.  I will take a look, test and reply again.

**Comment by maedoc** [comment]
I've pushed a new image, now named `ghcr.io/ins-amu/tvb-pipeline:latest`.  Can you try 
```
docker pull ghcr.io/ins-amu/tvb-pipeline:latest
docker rmi maedoc/tvb-make
docker tag ghcr.io/ins-amu/tvb-pipeline:latest maedoc/tvb-make
```
and then try again?

**Comment by nana-zhang** [comment]
Hello, I tried to use the following command to pull the image, but the following problem occurred:
![Screenshot from 2022-08-05 16-05-20](https://user-images.githubusercontent.com/70929994/183799271-f32a999f-aa72-4d55-b527-5b6150557f3a.png)
Is it because I don't have permission?

**Comment by nana-zhang** [comment]
Hello, I tried to use the following command to pull the image, but the following problem occurred. Is it because I don't have permission?
![Screenshot from 2022-08-10 10-47-22](https://user-images.githubusercontent.com/70929994/183799469-46b1ec78-0db5-4978-80a5-0d30341d6861.png)

**Comment by nana-zhang** [comment]
Hello, I've tried many methods, but still can't solve the above problem. I guess I don't have permission, so if you can help me if you're free, I'll be grateful.

**Comment by nana-zhang** [comment]
Hello，
 I guess you have set this image as private, so I have no permission to pull this image. Can you modify the permission?

**Comment by maedoc** [comment]
Sorry, wasn't intentional, can you try again?

**Comment by nana-zhang** [comment]
OK, I will try again.

**Comment by maedoc** [comment]
I’ll take a look as soon as possible.
